<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $news = Mage::registry('news'); ?>
<?php if (Mage::getStoreConfig('htmlcms_news/news/breadcrumbs')): ?>
    <div class="breadcrumbs">
        <?php $breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
        $breadcrumbs->addCrumb('home',array('label'=>Mage::helper('cms')->__('Home'),'title'=>Mage::helper('cms')->__('Home'),'link'=>Mage::getBaseUrl()));
        $breadcrumbs->addCrumb('News', array('label'=>$this->__('News'),'title'=>$this->__('News'),'link'=>Mage::getBaseUrl().'news'));
        foreach ($news['parent'] as $val) {
            $co = count($news['parent']);
            $breadcrumbs->addCrumb($co, end($news['parent']));
            unset($news['parent'][$co-1]);
        }
        $breadcrumbs->addCrumb('types', array('label'=>$news['title'],'title'=>$news['title']));
        echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();
        ?>
    </div>
<?php endif; ?>
<?php $nodata = Mage::registry('nodata');
if (isset ($nodata))
    echo $nodata; ?>
<article class="entry-news">
    <h1 class="entry-title">
        <?php echo $news['title'] ?>
    </h1>
    <?php if(isset($news['image']) && $news['image']!='') : ?>
        <?php $path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'image_news/'; ?>
        <figure class="entry-figure">
            <img src="<?php echo $path.'thumb/'.$news['image'] ?>" alt="<?php echo $news['title'] ?>">
        </figure>
    <?php endif; ?>
    <div class=“entry-content”>
        <?php echo $news['body'] ?>
    </div>
    <footer class="entry-footer">
        <time  datetime="<?php echo date('Y-m-d', strtotime($news['timestamp']))?>"><?php echo $this->formatDate($news['timestamp'], 'long', false); ?></time>
        <a class="button" href="<?php echo $this->getBaseUrl(); ?>news"><span><?php echo $this->__('Back to news')?></span></a>
    </footer>
</article>
<?php $socials = explode(',', Mage::getStoreConfig('htmlcms_news/news/social')); ?>
<?php foreach ($socials as $social):
    switch ($social){
        case 'facebook':?>
            <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:24px;height:24px;margin:0 6px 6px 0;padding:0;outline:none;background:url(<?php echo Mage::getBaseUrl('skin'); ?>frontend/default/default/htmlcms/icons.png) -0px 0 no-repeat" href="#" data-count="fb" onclick="window.open('http://www.facebook.com/sharer.php?s=100&amp;p[url]=<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($news['rewrite_id'])->getRequestPath()?>&amp;p[title]=<?php echo $news['title'] ?>&amp;p[summary]=<?php echo $news['description']; ?>&amp;p[images][0]=<?php echo $path.$news['image']; ?>', '_blank', 'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0');return false" title="<?php echo $this->__('Share on Facebook')?>" target="_blank"></a>
            <?php break;
        case 'twitter':?>
            <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:24px;height:24px;margin:0 6px 6px 0;padding:0;outline:none;background:url(<?php echo Mage::getBaseUrl('skin'); ?>frontend/default/default/htmlcms/icons.png) -72px 0 no-repeat" href="#" data-count="twi" onclick="window.open('https://twitter.com/intent/tweet?text=<?php echo $news['title'] ?>&amp;url=<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($news['rewrite_id'])->getRequestPath() ?>', '_blank', 'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0');return false" title="<?php echo $this->__('Share on Twitter')?>" target="_blank"></a>
            <?php break;
        case 'google':?>
            <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:24px;height:24px;margin:0 6px 6px 0;padding:0;outline:none;background:url(<?php echo Mage::getBaseUrl('skin'); ?>frontend/default/default/htmlcms/icons.png) -24px 0 no-repeat" href="#" onclick="window.open('https://plus.google.com/share?url=<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($news['rewrite_id'])->getRequestPath() ?>', '_blank', 'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0');return false" title="<?php echo $this->__('Share on Google+')?>" target="_blank"></a>
            <?php break;
        case 'pin':?>
            <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:24px;height:24px;margin:0 6px 6px 0;padding:0;outline:none;background:url(<?php echo Mage::getBaseUrl('skin'); ?>frontend/default/default/htmlcms/icons.png) -48px 0 no-repeat" href="#" data-count="pin" onclick="window.open('http://pinterest.com/pin/create/button/?url=<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($news['rewrite_id'])->getRequestPath() ?>&amp;media=<?php echo $path.$news['image']; ?>&amp;description=<?php echo $news['title'] ?>', '_blank', 'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=600, height=300, toolbar=0, status=0');return false" title="<?php echo $this->__('Pin It')?>" target="_blank"></a>
            <?php break;
        case 'print': ?>
            <a rel="nofollow" style="display:inline-block;vertical-align:bottom;width:24px;height:24px;margin:0 6px 6px 0;padding:0;outline:none;background:url(<?php echo Mage::getBaseUrl('skin'); ?>frontend/default/default/htmlcms/icons.png) -96px 0 no-repeat" href="#" onclick="print();return false" title="<?php echo $this->__('Print')?>" target="_blank"></a>
            <?php break;
    } ?>
<?php endforeach; ?>